name: 'JsonTo-Varialbe'
description: 'GitHub action to create workflow variables from a JSON input file'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filePath:
    description:  'Path to the json file'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -filePath '${{ inputs.filePath }}'
      shell: pwsh
