name: 'JsonTo-Variable'
description: 'GitHub action to create workflow variables from a JSON input file'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filePath:
    description: 'Path to the json file'
    required: true
    default: ''
  arraySeparator:
    description: 'arraySeperator for arrays'
    required: true
    default: ','
  outputs:
    description: 'Use variables in other jobs'
    default: false

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -filePath "${{ inputs.filePath }}" 
              -arraySeparator "${{ inputs.arraySeparator }}"
              -Outputs ${{ inputs.outputs }}
      shell: pwsh
