# This is a basic workflow to help you get started with Actions
name: JsonTo-Variable
on: push

jobs:
  template:
    name: Action Name
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats JsonTo-Variable
        uses: SecureHats/JsonTo-Variable@v0.0.1
        with:
          filePath: 'variables/env.json'
